# Generated by Django 6.0.6 on 2026-06-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_chatmessage_session_id_alter_chatmessage_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
